# Generated by Django 4.1.1 on 2022-09-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='ownerName',
            new_name='owner_name',
        ),
    ]
